### ISSUE TITLE
More than five sliding tab with equal width

### ISSUE THREAD

**Issue by mistrydarshan99** [nispok/slidingtabs#1]
I have a more than five sliding tab with equal width for that i set setDistributeEvenly(true) but tab cannot be scroll.I want also tab scroll if my device screen is small.

**Comment by wmora** [comment]
@mistrydarshan99 `setDistributeEvenly` does not allow scrolling, it is the expected behavior when you have a few tabs. If your tabs make your layout longer than the screen width they should all have the same width and allow scrolling and you don't have to call `setDistributeEvenly`.
